/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license.

# Nada Topology for Undirected Graphs

This file defines the closed neighborhood of a vertex in a simple graph and the
topology generated by the family of all closed neighborhoods (the Nada construction).
-/
import Mathlib.Combinatorics.SimpleGraph.Basic
import Mathlib.Topology.Order

open Set TopologicalSpace

namespace SimpleGraph

/-! ## Closed neighborhood in an undirected graph -/

/-- The closed neighborhood `N[v]` of a vertex `v` in a simple graph `G`:
the set `{v} ∪ {w | G.Adj v w}`. -/
def closedNeighborhood {V : Type*} (G : SimpleGraph V) (v : V) : Set V :=
  {v} ∪ G.neighborSet v

/-- The Nada subbase: the family `{N[v] | v ∈ V}` of closed neighborhoods. -/
def nadaSubbase {V : Type*} (G : SimpleGraph V) : Set (Set V) :=
  Set.range G.closedNeighborhood

/-- The Nada topology on the vertex set of an undirected graph:
the topology generated by the family of closed neighborhoods as a subbase.

This is the construction of Nada et al. (2018): take `S = {N[v] : v ∈ V}` as a subbase,
close under finite intersections to get a base, then close under arbitrary unions
to get a topology. Mathlib's `TopologicalSpace.generateFrom` does exactly this. -/
@[reducible]
def nadaTopology {V : Type*} (G : SimpleGraph V) : TopologicalSpace V :=
  TopologicalSpace.generateFrom G.nadaSubbase

/-- Every closed neighborhood is open in the Nada topology. -/
theorem closedNeighborhood_isOpen {V : Type*} (G : SimpleGraph V) (v : V) :
    @IsOpen V G.nadaTopology (G.closedNeighborhood v) :=
  GenerateOpen.basic _ ⟨v, rfl⟩

/-- The vertex itself belongs to its closed neighborhood. -/
theorem mem_closedNeighborhood_self {V : Type*} (G : SimpleGraph V) (v : V) :
    v ∈ G.closedNeighborhood v :=
  Or.inl (mem_singleton v)

end SimpleGraph
