/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license.

# Nada Topology for Directed Graphs

This file defines forward and backward closed neighborhoods for a directed graph
(`Digraph`), and the two topologies generated by the Nada procedure applied to each.
-/
import Mathlib.Combinatorics.Digraph.Basic
import Mathlib.Topology.Order

open Set TopologicalSpace

namespace Digraph

/-! ## Forward and backward closed neighborhoods -/

/-- The forward closed neighborhood `N⁺[v]` of a vertex `v` in a digraph `G`:
the set `{v} ∪ {w | G.Adj v w}` (out-neighbors plus the vertex itself). -/
def forwardClosedNhd {V : Type*} (G : Digraph V) (v : V) : Set V :=
  {v} ∪ {w | G.Adj v w}

/-- The backward closed neighborhood `N⁻[v]` of a vertex `v` in a digraph `G`:
the set `{v} ∪ {w | G.Adj w v}` (in-neighbors plus the vertex itself). -/
def backwardClosedNhd {V : Type*} (G : Digraph V) (v : V) : Set V :=
  {v} ∪ {w | G.Adj w v}

/-! ## Subbases -/

/-- The forward Nada subbase: `S⁺ = {N⁺[v] | v ∈ V}`. -/
def forwardSubbase {V : Type*} (G : Digraph V) : Set (Set V) :=
  Set.range G.forwardClosedNhd

/-- The backward Nada subbase: `S⁻ = {N⁻[v] | v ∈ V}`. -/
def backwardSubbase {V : Type*} (G : Digraph V) : Set (Set V) :=
  Set.range G.backwardClosedNhd

/-! ## Directed Nada topologies -/

/-- The forward Nada topology `τ⁺`: generated by the forward closed neighborhoods. -/
@[reducible]
def nadaForwardTopology {V : Type*} (G : Digraph V) : TopologicalSpace V :=
  TopologicalSpace.generateFrom G.forwardSubbase

/-- The backward Nada topology `τ⁻`: generated by the backward closed neighborhoods. -/
@[reducible]
def nadaBackwardTopology {V : Type*} (G : Digraph V) : TopologicalSpace V :=
  TopologicalSpace.generateFrom G.backwardSubbase

/-! ## Basic membership lemmas -/

theorem mem_forwardClosedNhd_self {V : Type*} (G : Digraph V) (v : V) :
    v ∈ G.forwardClosedNhd v :=
  Or.inl (mem_singleton v)

theorem mem_backwardClosedNhd_self {V : Type*} (G : Digraph V) (v : V) :
    v ∈ G.backwardClosedNhd v :=
  Or.inl (mem_singleton v)

/-- Every forward closed neighborhood is open in `τ⁺`. -/
theorem forwardClosedNhd_isOpen {V : Type*} (G : Digraph V) (v : V) :
    @IsOpen V G.nadaForwardTopology (G.forwardClosedNhd v) :=
  GenerateOpen.basic _ ⟨v, rfl⟩

/-- Every backward closed neighborhood is open in `τ⁻`. -/
theorem backwardClosedNhd_isOpen {V : Type*} (G : Digraph V) (v : V) :
    @IsOpen V G.nadaBackwardTopology (G.backwardClosedNhd v) :=
  GenerateOpen.basic _ ⟨v, rfl⟩

/-- For a symmetric digraph, forward and backward closed neighborhoods coincide. -/
theorem forwardClosedNhd_eq_backwardClosedNhd_of_symmetric {V : Type*}
    (G : Digraph V) (hsymm : ∀ v w, G.Adj v w → G.Adj w v) (v : V) :
    G.forwardClosedNhd v = G.backwardClosedNhd v := by
  ext w
  simp only [forwardClosedNhd, backwardClosedNhd, mem_union, mem_singleton_iff, mem_setOf_eq]
  constructor
  · rintro (rfl | h)
    · left; rfl
    · right; exact hsymm v w h
  · rintro (rfl | h)
    · left; rfl
    · right; exact hsymm w v h

end Digraph
